# Generated by Django 5.2.17 on 2026-09-11 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SourceFetch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("game_detail", "game_detail"),
                            ("platform_userscore", "platform_userscore"),
                        ],
                        max_length=32,
                    ),
                ),
                ("url", models.TextField()),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("http_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("response_sha256", models.CharField(blank=True, max_length=64, null=True)),
                ("parser_contract_version", models.CharField(max_length=32)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("succeeded", "succeeded"),
                            ("failed", "failed"),
                            ("invalid", "invalid"),
                        ],
                        max_length=16,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("metacritic", "metacritic")], default="metacritic", max_length=32
                    ),
                ),
                ("source_game_id", models.CharField(max_length=64)),
                ("canonical_locator", models.CharField(max_length=512)),
                ("title", models.CharField(max_length=255)),
                ("cover_url", models.TextField(blank=True, null=True)),
                ("developer", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("video_embed_url", models.TextField(blank=True, null=True)),
                ("video_content_url", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_changed_fetch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.sourcefetch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("metacritic", "metacritic")], default="metacritic", max_length=32
                    ),
                ),
                ("locator", models.CharField(max_length=512)),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="catalog.game",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "locator"), name="uq_game_alias_source_locator"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GamePlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("metacritic", "metacritic")], default="metacritic", max_length=32
                    ),
                ),
                ("source_platform_id", models.CharField(max_length=64)),
                ("source_game_platform_id", models.CharField(max_length=64)),
                ("slug", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=128)),
                ("metascore", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "userscore",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
                ),
                ("critic_reviews_path", models.CharField(blank=True, max_length=512, null=True)),
                ("user_reviews_path", models.CharField(blank=True, max_length=512, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platforms",
                        to="catalog.game",
                    ),
                ),
                (
                    "last_changed_fetch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.sourcefetch",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("game", "source_platform_id"),
                        name="uq_game_platform_game_source_platform",
                    ),
                    models.UniqueConstraint(
                        fields=("source", "source_game_platform_id"),
                        name="uq_game_platform_source_related_id",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("metascore__isnull", True),
                            models.Q(("metascore__gte", 0), ("metascore__lte", 100)),
                            _connector="OR",
                        ),
                        name="ck_game_platform_metascore_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("userscore__isnull", True),
                            models.Q(("userscore__gte", 0), ("userscore__lte", 10)),
                            _connector="OR",
                        ),
                        name="ck_game_platform_userscore_range",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.UniqueConstraint(
                fields=("source", "source_game_id"), name="uq_game_source_source_game_id"
            ),
        ),
    ]
