# Generated by Django 5.2.17 on 2026-09-11 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gameplatform",
            name="last_changed_fetch",
        ),
        migrations.AddField(
            model_name="gameplatform",
            name="metascore_last_changed_fetch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="catalog.sourcefetch",
            ),
        ),
        migrations.AddField(
            model_name="gameplatform",
            name="userscore_last_changed_fetch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="catalog.sourcefetch",
            ),
        ),
    ]
