# Generated by Django 5.2.17 on 2026-09-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_remove_gameplatform_last_changed_fetch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcefetch",
            name="kind",
            field=models.CharField(
                choices=[
                    ("game_detail", "game_detail"),
                    ("platform_userscore", "platform_userscore"),
                    ("new_releases", "new_releases"),
                    ("browse_page", "browse_page"),
                ],
                max_length=32,
            ),
        ),
    ]
