# Generated by Django 5.2.17 on 2026-09-12 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_sourcefetch_kind"),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcefetch",
            name="attempt_no",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sourcefetch",
            name="collection_generation",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sourcefetch",
            name="fencing_token",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sourcefetch",
            name="item_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sourcefetch",
            name="page_ordinal",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sourcefetch",
            name="reported_total",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sourcefetch",
            name="review_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fetch_attempts",
                to="reviews.reviewcollectionjob",
            ),
        ),
        migrations.AlterField(
            model_name="sourcefetch",
            name="kind",
            field=models.CharField(
                choices=[
                    ("game_detail", "game_detail"),
                    ("platform_userscore", "platform_userscore"),
                    ("new_releases", "new_releases"),
                    ("browse_page", "browse_page"),
                    ("review_page", "review_page"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcefetch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("review_job__isnull", False)),
                fields=("review_job", "collection_generation", "page_ordinal", "attempt_no"),
                name="uq_source_fetch_review_attempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcefetch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("outcome", "succeeded"), ("review_job__isnull", False)),
                fields=("review_job", "collection_generation", "page_ordinal"),
                name="uq_source_fetch_review_accepted_page",
            ),
        ),
    ]
