# Generated by Django 5.2.17 on 2026-09-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_sourcefetch_review_page_evidence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcefetch",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("started", "started"),
                    ("abandoned", "abandoned"),
                    ("superseded", "superseded"),
                    ("succeeded", "succeeded"),
                    ("failed", "failed"),
                    ("invalid", "invalid"),
                ],
                max_length=16,
            ),
        ),
    ]
