# Generated by Django 5.2.17 on 2026-09-14 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_alter_sourcefetch_outcome"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="genres",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="game",
            name="genres_last_changed_fetch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="catalog.sourcefetch",
            ),
        ),
    ]
