# Generated by Django 5.2.17 on 2026-09-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_game_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="content_rating",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="publishers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="game",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
