# Generated by Django 5.2.17 on 2026-09-21 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_unescape_game_descriptions"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("model_id", models.CharField(max_length=128)),
                ("text_sha256", models.CharField(max_length=64)),
                ("vector", models.BinaryField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="catalog.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameNeighbors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("policy_version", models.CharField(max_length=32)),
                ("neighbors", models.JSONField(blank=True, default=list)),
                ("computed_at", models.DateTimeField()),
                (
                    "game",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="neighbors",
                        to="catalog.game",
                    ),
                ),
            ],
        ),
    ]
