# Generated by Django 5.2.17 on 2026-09-24 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_game_embedding_and_neighbors"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameembedding",
            name="kind",
            field=models.CharField(default="description", max_length=16),
        ),
        migrations.AlterField(
            model_name="gameembedding",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="embeddings",
                to="catalog.game",
            ),
        ),
        migrations.AddField(
            model_name="gameneighbors",
            name="inputs_sha256",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddConstraint(
            model_name="gameembedding",
            constraint=models.UniqueConstraint(
                fields=("game", "kind"), name="catalog_embedding_game_kind"
            ),
        ),
    ]
