# Generated by Django 5.2.17 on 2026-09-11 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("processing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewCollectionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[("critic", "critic"), ("user", "user")], max_length=8
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("running", "running"),
                            ("complete", "complete"),
                            ("empty", "empty"),
                            ("retryable", "retryable"),
                            ("unstable", "unstable"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "daily_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_jobs",
                        to="processing.dailycandidate",
                    ),
                ),
                (
                    "game_platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_jobs",
                        to="catalog.gameplatform",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("daily_candidate", "game_platform", "audience"),
                        name="uq_review_job_candidate_platform_audience",
                    )
                ],
            },
        ),
    ]
