# Generated by Django 5.2.17 on 2026-09-12 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_sourcefetch_review_page_evidence"),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviewcollectionjob",
            name="created_at",
        ),
        migrations.AddField(
            model_name="reviewcollectionjob",
            name="attempt_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reviewcollectionjob",
            name="available_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewcollectionjob",
            name="collection_generation",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reviewcollectionjob",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewcollectionjob",
            name="duplicate_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reviewcollectionjob",
            name="fencing_token",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reviewcollectionjob",
            name="fetched_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reviewcollectionjob",
            name="last_error",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="reviewcollectionjob",
            name="lease_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewcollectionjob",
            name="next_cursor",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewcollectionjob",
            name="page_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reviewcollectionjob",
            name="reported_total",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewcollectionjob",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewcollectionjob",
            name="unique_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reviewcollectionjob",
            name="visited_page_fingerprints",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[("critic", "critic"), ("user", "user")], max_length=8
                    ),
                ),
                ("source_review_id", models.CharField(blank=True, max_length=128, null=True)),
                ("identity_key", models.CharField(max_length=140)),
                ("author_label", models.CharField(blank=True, max_length=255, null=True)),
                ("score_label", models.CharField(blank=True, max_length=32, null=True)),
                ("date_label", models.CharField(blank=True, max_length=64, null=True)),
                ("text_original", models.TextField()),
                ("content_sha256", models.CharField(max_length=64)),
                ("first_seen_at", models.DateTimeField()),
                (
                    "game_platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="catalog.gameplatform",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by",
                        to="reviews.review",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewCorpus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[("critic", "critic"), ("user", "user")], max_length=8
                    ),
                ),
                ("policy_version", models.CharField(max_length=32)),
                ("source_set_fingerprint", models.CharField(max_length=64)),
                ("model_input_fingerprint", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("complete_route_count", models.PositiveIntegerField()),
                ("empty_route_count", models.PositiveIntegerField()),
                ("reported_count", models.PositiveIntegerField()),
                ("fetched_count", models.PositiveIntegerField()),
                ("unique_count", models.PositiveIntegerField()),
                ("deduplicated_count", models.PositiveIntegerField()),
                ("selected_count", models.PositiveIntegerField()),
                ("tokenizer_id", models.CharField(max_length=32)),
                ("tokenizer_version", models.CharField(max_length=32)),
                ("raw_prompt_tokens", models.PositiveIntegerField()),
                ("guarded_prompt_tokens", models.PositiveIntegerField()),
                ("completion_reservation", models.PositiveIntegerField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_corpora",
                        to="catalog.game",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "review corpora",
            },
        ),
        migrations.CreateModel(
            name="ReviewCorpusItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ordinal", models.PositiveSmallIntegerField()),
                ("prompt_review_id", models.CharField(max_length=8)),
                ("input_text", models.TextField()),
                ("input_token_count", models.PositiveIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("was_truncated", models.BooleanField()),
                (
                    "corpus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="reviews.reviewcorpus",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corpus_items",
                        to="reviews.review",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("collection_generation", models.PositiveIntegerField()),
                ("page_position", models.PositiveIntegerField()),
                ("route_global_position", models.PositiveIntegerField()),
                (
                    "collection_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="reviews.reviewcollectionjob",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="reviews.review",
                    ),
                ),
                (
                    "source_fetch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_observations",
                        to="catalog.sourcefetch",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("game_platform", "audience", "identity_key", "content_sha256"),
                name="uq_review_platform_audience_identity_content",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewcorpus",
            constraint=models.UniqueConstraint(
                fields=("game", "audience", "policy_version", "source_set_fingerprint"),
                name="uq_review_corpus_game_audience_policy_fingerprint",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewcorpusitem",
            constraint=models.UniqueConstraint(
                fields=("corpus", "ordinal"), name="uq_corpus_item_ordinal"
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewcorpusitem",
            constraint=models.UniqueConstraint(
                fields=("corpus", "prompt_review_id"), name="uq_corpus_item_prompt_review_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewcorpusitem",
            constraint=models.UniqueConstraint(
                fields=("corpus", "review"), name="uq_corpus_item_review"
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewobservation",
            constraint=models.UniqueConstraint(
                fields=("source_fetch", "page_position"),
                name="uq_review_observation_fetch_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewobservation",
            constraint=models.UniqueConstraint(
                fields=("collection_job", "collection_generation", "review"),
                name="uq_review_observation_job_generation_review",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewobservation",
            constraint=models.UniqueConstraint(
                fields=("collection_job", "collection_generation", "route_global_position"),
                name="uq_review_observation_job_generation_position",
            ),
        ),
    ]
