# Generated by Django 5.2.17 on 2026-09-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0004_review_version_fingerprint"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrichmentTurn",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "next_kind",
                    models.CharField(
                        choices=[("review", "review"), ("summary", "summary")],
                        default="review",
                        max_length=8,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="enrichment_turn_singleton"
                    )
                ],
            },
        ),
    ]
