# Generated by Django 5.2.17 on 2026-09-14 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_alter_sourcefetch_outcome"),
        ("reviews", "0005_enrichmentturn"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewCorpusHead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[("critic", "critic"), ("user", "user")], max_length=8
                    ),
                ),
                ("collection_checkpoint", models.CharField(max_length=64)),
                (
                    "corpus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="heads",
                        to="reviews.reviewcorpus",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corpus_heads",
                        to="catalog.game",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("game", "audience"), name="uq_corpus_head_game_audience"
                    )
                ],
            },
        ),
    ]
