# Generated by Django 5.2.17 on 2026-09-12 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0004_sourcefetch_review_page_evidence"),
        ("reviews", "0002_review_collection_and_corpus"),
    ]

    operations = [
        migrations.CreateModel(
            name="SummaryJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[("critic", "critic"), ("user", "user")], max_length=8
                    ),
                ),
                ("input_fingerprint", models.CharField(max_length=64)),
                ("contour_fingerprint", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("running", "running"),
                            ("succeeded", "succeeded"),
                            ("insufficient_data", "insufficient_data"),
                            ("retryable", "retryable"),
                            ("delayed_capacity", "delayed_capacity"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("available_at", models.DateTimeField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("fencing_token", models.PositiveBigIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="summary_jobs",
                        to="catalog.game",
                    ),
                ),
                (
                    "source_corpus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="summary_jobs",
                        to="reviews.reviewcorpus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SummaryAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("attempt_no", models.PositiveIntegerField()),
                ("provider", models.CharField(default="groq", max_length=32)),
                ("api_kind", models.CharField(default="chat_completions", max_length=32)),
                ("requested_model", models.CharField(max_length=64)),
                ("returned_model", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "provider_system_fingerprint",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("contour_versions", models.JSONField()),
                ("generation_params", models.JSONField()),
                ("estimated_prompt_tokens", models.PositiveIntegerField()),
                ("reserved_total_tokens", models.PositiveIntegerField()),
                ("actual_prompt_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("actual_completion_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("actual_total_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("succeeded", "succeeded"),
                            ("insufficient_data", "insufficient_data"),
                            ("retryable", "retryable"),
                            ("delayed_capacity", "delayed_capacity"),
                            ("failed", "failed"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="summaries.summaryjob",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("model", "model"), ("rule", "rule")],
                        default="model",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ok", "ok"), ("insufficient_data", "insufficient_data")],
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField()),
                ("insufficient_reason", models.CharField(blank=True, max_length=64, null=True)),
                ("canonical_output_fingerprint", models.CharField(max_length=64)),
                ("normalization_notes", models.JSONField(blank=True, default=list)),
                (
                    "successful_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="summaries.summaryattempt",
                    ),
                ),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="summary",
                        to="summaries.summaryjob",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SummaryClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "polarity",
                    models.CharField(
                        choices=[("like", "like"), ("dislike", "dislike")], max_length=8
                    ),
                ),
                ("ordinal", models.PositiveSmallIntegerField()),
                ("claim", models.CharField(max_length=160)),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to="summaries.reviewsummary",
                    ),
                ),
                (
                    "support_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supported_claims",
                        to="reviews.reviewcorpusitem",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("summary", "polarity", "ordinal"),
                        name="uq_summary_claim_polarity_ordinal",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="summaryjob",
            constraint=models.UniqueConstraint(
                fields=("game", "audience", "input_fingerprint", "contour_fingerprint"),
                name="uq_summary_job_game_audience_input_contour",
            ),
        ),
        migrations.AddConstraint(
            model_name="summaryattempt",
            constraint=models.UniqueConstraint(
                fields=("job", "attempt_no"), name="uq_summary_attempt_job_no"
            ),
        ),
    ]
