# Generated by Django 5.2.17 on 2026-09-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("summaries", "0002_summaryjob_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="summaryattempt",
            name="fencing_token",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="summaryattempt",
            name="rate_limit_headers",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="summaryattempt",
            name="raw_prompt_tokens",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="summaryattempt",
            name="request_sha256",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="summaryattempt",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("succeeded", "succeeded"),
                    ("insufficient_data", "insufficient_data"),
                    ("retryable", "retryable"),
                    ("delayed_capacity", "delayed_capacity"),
                    ("failed", "failed"),
                    ("abandoned", "abandoned"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
