# Generated by Django 5.2.17 on 2026-09-11 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("business_date", models.DateField()),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("new_releases_pending", "new_releases_pending"),
                            ("browse", "browse"),
                            ("exhausted", "exhausted"),
                        ],
                        default="new_releases_pending",
                        max_length=32,
                    ),
                ),
                ("exhausted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("business_date", "timezone"), name="uq_daily_cycle_business_date_tz"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_order", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("processing", "processing"),
                            ("processed", "processed"),
                            ("retryable", "retryable"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidates",
                        to="catalog.game",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidates",
                        to="processing.dailycycle",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cycle", "game"), name="uq_daily_candidate_cycle_game"
                    ),
                    models.UniqueConstraint(
                        fields=("cycle", "source_order"), name="uq_daily_candidate_cycle_order"
                    ),
                ],
            },
        ),
    ]
