# Generated by Django 5.2.17 on 2026-09-11 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("trigger_key", models.CharField(max_length=64, unique=True)),
                ("scheduled_slot", models.DateTimeField()),
                ("business_day", models.DateField(blank=True, null=True)),
                ("fencing_token", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("running", "running"),
                            ("succeeded", "succeeded"),
                            ("partial", "partial"),
                            ("failed", "failed"),
                            ("skipped_duplicate", "skipped_duplicate"),
                            ("skipped_overlap", "skipped_overlap"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("selected_count", models.PositiveIntegerField(default=0)),
                ("processed_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="dailycycle",
            name="exhausted",
        ),
        migrations.AddField(
            model_name="dailycandidate",
            name="attempt_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailycycle",
            name="browse_next_page",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="ProcessingLease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("resource", models.CharField(default="ingestion", max_length=32, unique=True)),
                ("fencing_token", models.PositiveBigIntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="processing.processingrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoreAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("attempt_no", models.PositiveIntegerField()),
                ("fencing_token", models.PositiveBigIntegerField()),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[("succeeded", "succeeded"), ("failed", "failed")],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="processing.dailycandidate",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="core_attempts",
                        to="processing.processingrun",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("candidate", "attempt_no"), name="uq_core_attempt_candidate_no"
                    )
                ],
            },
        ),
    ]
