# Generated by Django 5.2.17 on 2026-09-16 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processing", "0002_processingrun_remove_dailycycle_exhausted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingrun",
            name="batch_frozen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ProcessHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("scheduler", "scheduler"), ("worker", "worker")], max_length=16
                    ),
                ),
                ("slot", models.CharField(default="main", max_length=32)),
                ("instance_id", models.UUIDField()),
                ("generation", models.PositiveBigIntegerField(default=1)),
                ("started_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("last_progress_at", models.DateTimeField()),
                ("mode", models.CharField(default="idle", max_length=16)),
                ("stage", models.CharField(default="idle", max_length=32)),
                ("run_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("job_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("deadline_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("role", "slot"), name="uq_process_role_slot")
                ],
            },
        ),
        migrations.CreateModel(
            name="RunCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="processing.dailycandidate",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batch",
                        to="processing.processingrun",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("run", "candidate"), name="uq_run_candidate"),
                    models.UniqueConstraint(fields=("run", "position"), name="uq_run_position"),
                    models.CheckConstraint(
                        condition=models.Q(("position__gte", 1), ("position__lte", 20)),
                        name="run_position_limit",
                    ),
                ],
            },
        ),
    ]
