# Generated by Django 5.2.17 on 2026-09-16 16:38; BON-22 manual-run trigger.

import django.db.models.deletion
from django.apps.registry import Apps
from django.conf import settings
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def seed_admission_row(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """The singleton lock row is created here (under the migrate role) so web -- granted only
    `UPDATE` on this table, never `INSERT` -- can lock it without needing to create it."""
    trigger_admission_model = apps.get_model("processing", "TriggerAdmission")
    trigger_admission_model.objects.get_or_create(resource="manual_trigger")


class Migration(migrations.Migration):
    dependencies = [
        ("processing", "0003_monitoring_progress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TriggerAdmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "resource",
                    models.CharField(default="manual_trigger", max_length=32, unique=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="processingrun",
            name="trigger_kind",
            field=models.CharField(
                choices=[("scheduled", "scheduled"), ("manual", "manual")],
                default="scheduled",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="processingrun",
            name="scheduled_slot",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="LoginFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fingerprint", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["fingerprint", "created_at"], name="processing__fingerp_1dee41_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ManualRunRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("request_id", models.UUIDField(unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("claimed", "claimed"),
                            ("completed", "completed"),
                            ("conflict", "conflict"),
                            ("expired", "expired"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("reason_code", models.CharField(blank=True, max_length=32, null=True)),
                ("created_at", models.DateTimeField()),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manual_requests",
                        to="processing.processingrun",
                    ),
                ),
            ],
            options={
                "permissions": [("trigger_run", "Can trigger a manual processing run")],
                "constraints": [
                    models.UniqueConstraint(fields=("run",), name="uq_manual_request_run")
                ],
            },
        ),
        migrations.RunPython(seed_admission_row, migrations.RunPython.noop),
    ]
