# Generated by Django 5.2.17 on 2026-10-03 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0010_embedding_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="LetsPlay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("searching", "searching"),
                            ("listening", "listening"),
                            ("concluding", "concluding"),
                            ("done", "done"),
                            ("not_found", "not_found"),
                            ("failed", "failed"),
                        ],
                        default="searching",
                        max_length=16,
                    ),
                ),
                ("policy_version", models.CharField(max_length=16)),
                ("available_at", models.DateTimeField(blank=True, null=True)),
                ("refresh_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("searched_at", models.DateTimeField(blank=True, null=True)),
                ("shortlist", models.JSONField(blank=True, default=list)),
                ("checks", models.JSONField(blank=True, default=list)),
                ("video_id", models.CharField(blank=True, max_length=16, null=True)),
                ("video_title", models.CharField(blank=True, max_length=200, null=True)),
                ("channel", models.CharField(blank=True, max_length=120, null=True)),
                ("views", models.PositiveBigIntegerField(blank=True, null=True)),
                ("seconds", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "game",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="letsplay",
                        to="catalog.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LetsPlayTranscript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("video_id", models.CharField(max_length=16)),
                (
                    "source",
                    models.CharField(
                        choices=[("captions", "captions"), ("whisper", "whisper")], max_length=16
                    ),
                ),
                ("language", models.CharField(blank=True, max_length=32, null=True)),
                ("seconds_covered", models.FloatField()),
                ("text", models.TextField()),
                ("text_sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField()),
                (
                    "letsplay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transcripts",
                        to="letsplays.letsplay",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LetsPlayConclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("contour_fingerprint", models.CharField(max_length=64)),
                ("contour_versions", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[("sufficient", "sufficient"), ("insufficient", "insufficient")],
                        max_length=16,
                    ),
                ),
                ("verdict", models.CharField(blank=True, max_length=300)),
                ("sponsored", models.BooleanField(default=False)),
                ("opinions", models.JSONField(blank=True, default=list)),
                ("returned_model", models.CharField(blank=True, max_length=64, null=True)),
                ("prompt_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("completion_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("generated_at", models.DateTimeField()),
                (
                    "letsplay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conclusions",
                        to="letsplays.letsplay",
                    ),
                ),
                (
                    "transcript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conclusions",
                        to="letsplays.letsplaytranscript",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("youtube_api", "youtube_api"),
                            ("captions", "captions"),
                            ("audio", "audio"),
                            ("whisper", "whisper"),
                            ("chat", "chat"),
                        ],
                        max_length=16,
                    ),
                ),
                ("video_id", models.CharField(blank=True, max_length=16, null=True)),
                ("units", models.PositiveIntegerField(default=0)),
                ("actual_units", models.PositiveIntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("outcome", models.CharField(blank=True, max_length=24, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64, null=True)),
                ("headers", models.JSONField(blank=True, default=dict)),
                (
                    "letsplay",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calls",
                        to="letsplays.letsplay",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="letsplay",
            index=models.Index(fields=["state", "available_at"], name="letsplay_due"),
        ),
        migrations.AddConstraint(
            model_name="letsplayconclusion",
            constraint=models.UniqueConstraint(
                fields=("transcript", "contour_fingerprint"),
                name="uq_letsplay_conclusion_transcript_contour",
            ),
        ),
        migrations.AddIndex(
            model_name="providercall",
            index=models.Index(fields=["kind", "started_at"], name="provider_call_window"),
        ),
    ]
