# Generated by Django 5.2.17 on 2026-10-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letsplays", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providercall",
            name="kind",
            field=models.CharField(
                choices=[
                    ("youtube_api", "youtube_api"),
                    ("video", "video"),
                    ("captions", "captions"),
                    ("audio", "audio"),
                    ("whisper", "whisper"),
                    ("chat", "chat"),
                ],
                max_length=16,
            ),
        ),
    ]
